spring:
  #激活哪一个环境的配置文件
  profiles: dev
  #Druid连接池配置
  datasource:
    druid:
      #连接信息
      url: jdbc:mysql://localhost:3306/zc-wx?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      #连接池配置
      min-idle: 5
      initial-size: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #监控
      filter:
        wall:
          enabled: true
#日志
logging:
  #日志输出路径
  path: log
  level:
    com:
      admin:
        mapper: debug
